/* ==========================================================
   EDIT EVERYTHING HERE - names, photos, captions, story, letters,
   songs, wishes. No need to touch main.js.
   Songs: put your own legally obtained audio file path/link in songs[].src
   Photos: replace files in /images (keep the same names) or edit the list.
   ========================================================== */
const CFG={
 herName:"Khushboo",nicknames:["Heer","Bby","Biwi","Apsara"],birthday:"10-14",from:"Krishna",
 photos:[
  "images/her-01.jpg",
  "images/her-02.jpg",
  "images/her-03.jpg",
  "images/her-04.jpg",
  "images/her-05.jpg",
  "images/her-06.jpg",
  "images/her-07.jpg",
  "images/her-08.jpg",
  "images/her-09.jpg",
  "images/her-10.jpg",
  "images/her-11.jpg",
  "images/her-12.jpg"
 ],
 captions:["This smile >>> everything.","One of my favourite versions of you.","How are you even this pretty?","A memory I would happily relive.","My favourite person, captured in one frame.","You, being completely you.","This one gets me every time.","Little flower, big smile.","Soft, just like you.","The nerdy cutie edition.","Pure elegance.","Okay, this one is just unfair."],
 chapterTitles:["The Beginning","Little Wonder","The Quiet Growth","Your Spark","The Dreamer","Home in Her","A Laugh Like Yours","Strength in Silence","Finding Herself","What You Love","A Heart Like Yours","Softness That Stays","A Brave New Chapter","Small Wins, Big Strength","Becoming","Kindness in Motion","Almost Eighteen","Eighteen & Beautiful"],
 timeline:[["The Beginning", "where it all started", "I don't need a date to remember this. I just remember that something quietly changed, and I'm really glad it did."], ["When You Became Someone Special", "the moment it clicked", "Somewhere between the talks and the laughs, you stopped being just someone I knew. You became someone I look forward to."], ["The Conversations I Never Wanted To End", "one more minute, always", "Those talks where time disappeared. I'd say goodnight and still want five more minutes."], ["The Laughs", "my favourite sound", "The kind where you can't even explain what was funny. Those are the ones I keep."], ["The Random Calls", "for no reason at all", "No big topic, nothing important. Somehow those were the best ones."], ["The Little Things", "tiny but huge", "The small stuff, like how you say something, or a look you give. I notice all of it."], ["The Memories I Still Smile About", "still on replay", "I go back to them sometimes, and every time I end up smiling."]],
 chNotes:["I wasn't there for this one, but I like imagining her. Small, curious, with no idea she'd grow into someone this loved.", "Growing up isn't easy. I hope the little you was always told she was enough.", "Even then, you were slowly turning into the person you are today.", "The way you speak, the way you think. It was always yours.", "Some dreams you kept close. I hope you give them room to grow.", "I hope you've always had people who felt like home.", "The laughs. Yours is one of my favourite things in the world.", "The hard days you got through quietly. I see how strong you are.", "Learning who you are takes time. Take all of it.", "The things you love say so much about your heart.", "Your strength isn't loud. It's steady, and it's real.", "Somehow you kept your softness. Please never lose it.", "Every new beginning looks a little scary. You're braver than you think.", "Even the little wins count. I'm proud of every one.", "I can't wait to watch who you become.", "Your kindness is the first thing people feel around you.", "So close now. Almost eighteen, and already so much of yourself.", "Here you are. 18. Beautiful, brave, and completely yourself. Happy birthday."],
 love:[["Your smile", "It changes the whole mood of a room. Mine too, every time."], ["The way you talk", "The way you say things, your tone, your little pauses. I could listen for hours."], ["Your little reactions", "The tiny expressions you don't even notice. They're my favourite."], ["Your kindness", "You care about people for real, not for show."], ["Your ambition", "You want more from life, and you're allowed to. I love that about you."], ["Your emotional side", "You feel deeply. That's not a weakness. It's one of your best parts."], ["Your silly side", "When you stop being serious and just become silly. That version of you is gold."], ["Your strength", "You get through things quietly, and you keep going."], ["How you make ordinary moments special", "A normal day just feels better with you in it."], ["The way you care about people", "You notice people. That's rarer than you think."], ["The person you are becoming", "I'm really excited to see who she turns out to be."]],
 memories:["Remember this day? I do. Every little part of it.", "I still smile when I think about this.", "One of those completely ordinary moments that became special.", "You probably don't even realize how much this moment meant to me.", "Your laugh that day. I'd replay it if I could.", "Nothing big happened. It was just you, and that was enough.", "I think about the little things more than the big ones.", "Some days are quiet and still end up being my favourites."],
 openWhen:[["Open when you're having a bad day", "Hey. Bad days happen, and they don't mean anything about you. You don't have to fix it today. Drink some water, breathe, and be gentle with yourself. Tomorrow doesn't need today's mood."], ["Open when you miss me", "Then smile a little, because it means we've got something good. Send a message if you want to, or don't. Both are fine. I'm happy either way."], ["Open when you're stressed", "One thing at a time. You've handled hard things before and you'll handle this too. Take a break, stretch, eat something. You're doing better than you think."], ["Open when you need motivation", "Your dreams are bigger than your fears. Do the next small thing, then the next. I want to see you win."], ["Open when you feel like giving up", "Rest if you're tired. Resting is not quitting. You've come further than you realize, and you don't have to prove anything today."], ["Open when you want to smile", "Think of your own laugh. Now imagine hearing it from across the room. That's why I smile."], ["Open when you just want to feel loved", "You are. On the good days, and on the days you forget. Nothing about that is conditional."]],
 bad:["On the days when you don't recognize yourself, I hope you remember that you are still you. Still worthy. Still important. Still deserving of kindness.","You don't have to be happy, productive, beautiful, strong or perfect every day.","And if one day you feel like talking, I'll listen.","If you don't feel like talking, that's okay too.","If you need space, I'll respect it.","If you need someone beside you, I'll be there."],
 letter:["My Heer,","I wanted you to read this slowly, so get comfortable. There's no rush.","Happy 18th birthday. I keep trying to find the right words for what you mean to me, and I never quite get there. So I'll just be honest. You are one of the best things that has happened to me. The way you laugh, the way you talk, your tiny reactions, the way you make ordinary moments feel like they matter. I'm so grateful for every memory we've made, and I smile at a lot of them even now.","I'm proud of the person you're becoming. Not the version of you that has it all figured out, because nobody does. I mean the real you, who keeps growing, keeps trying, and keeps being kind even when it's hard.","You never have to be perfect. You can have bad days. You can change your mind, take your time, and put your studies and your dreams first. Your feelings matter. You never have to perform happiness for me.","I don't want this birthday to be about expectations. I just want you to smile, and to feel celebrated. You never have to rush your feelings for me. I would rather give you time than ask you for something before you're ready. I want the people around you to feel like places where you can breathe, and I want to be one of them.","Whatever version of yourself you are on a particular day, I hope you always know she deserves kindness. I don't want to be someone you have to convince yourself to feel safe around. I want my actions, slowly and consistently, to speak for themselves.","You don't have to promise me anything today. Just be you.","Happy 18th birthday, my Heer.","Keep smiling. Keep growing. Keep becoming the person you want to be.","Always cheering for you,<br>Your Romeo ♡"],
 perfect:["You can make mistakes.","You can be confused.","You can have bad days.","You can change your mind.","You can take your time.","You can focus on your studies.","You can have your own dreams.","You can have your own space.","You don't need to keep reassuring me."],
 songs:[{t:"Love Story",a:"Taylor Swift",src:"",q:"Some songs just sound different when they remind you of someone."},{t:"Divine",a:"Krishna Hazar",src:"",q:"And somehow, this one feels like us."}],
 wishes:["I hope you become everything you dream of becoming.","I hope you never lose your softness.","I hope you find people who celebrate your happiness.","I hope you never shrink yourself to fit somewhere.","I hope you keep choosing yourself.","I hope you laugh more.","I hope you travel and try new things.","I hope your dreams become bigger than your fears.","I hope you are surrounded by people who make you feel safe.","I hope this year gives you countless reasons to smile.","Most of all, I hope you remain yourself."],
 promises:["I promise to listen.","I promise to respect your space.","I promise not to make every feeling a problem that needs fixing.","I promise to celebrate your wins.","I promise to respect your dreams.","I promise to keep learning.","I promise to let my actions speak louder than my words.","I promise to never make your birthday about what I want from you."],
 qa:[["Do you have to be happy every day?","No."],["Do you have to have everything figured out?","Absolutely not."],["Do you have to be perfect?","Never."],["Can you take your time?","Always."],["Will you still be celebrated on difficult days?","Always."]],
 future:"I want to see you win, even beyond me. Your education, your career, your independence, your friendships, your confidence. All of it belongs to you. I hope you chase every dream without shrinking any of them, that you're surrounded by people who cheer for you loudly, and that someday you look back and feel proud of every brave choice you made. Whatever you become, I'll be one of the people clapping.",
 finale:["Thank you for existing.","Thank you for every laugh.","Every conversation.","Every memory.","Every little moment that became a big memory for me.","And thank you for being you.","Happy Birthday, My Heer ♡","From your Romeo."]
};
